name = "workers-airtable-form"
type = "javascript"

account_id = "5b1c421cc583b3f49d37a04912fd9474"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "app0vKWrtWDEoRBQm"
AIRTABLE_TABLE_NAME = "Users"
FORM_URL = "https://workers-airtable-form-7cj.pages.dev/"
